
title = "La Casa Della Polemica"
author = "Matteo 'El Glabro' Castellani"
#copyright = "2020-2021"
description = "Esclusivamente Over-IP"
profilePicture = "images/profile.jpg"
mainSections = ["post"]
doNotLoadAnimations = false
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

#[[socialIcons]]
#icon = "fab fa-mastodon"
#title = "Mastodon"
#url = "Quando mi decido"
